<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [
    <!ELEMENT deportistas (deportista+)>
    <!ELEMENT deportista (nombre,deporte)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT deporte (#PCDATA)>
]>
<deportistas>
    <deportista>
        <nombre>Jesse Owens</nombre>
        <deporte>Atletismo</deporte>
    </deportista>
    <deportista>
        <nombre>Mark Spitz</nombre>
        <deporte>Natacion</deporte>
    </deportista>
</deportistas>